# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Akash
email: akashshekara1212@gmail.com
url: "http://Shakira4242.github.io" # the base hostname & protocol for your site
twitter_username: akashshekara121
github_username:  Shakira4242

# Build settings
markdown: kramdown
